= Asciidoctor Backends

In this repository, you'll find an assortment of backend templates for generating different output formats from AsciiDoc that you can use with the template converter in https://github.com/asciidoctor/asciidoctor[Asciidoctor].
These examples demonstrate how to make an html5 or docbook45 converter similar to the ones in Asciidoctor using purely templates, as well as how to use templates to generate HTML5 presentations from AsciiDoc.

Please note that these templates are only meant to be examples.
They are not activately maintained, are not production ready, and are not intended to be a drop-in replacement for the official converters.
They are provided merely as a reference and starting point for creating your own template-based converter.

Since the template converter in Asciidoctor works on a per-element basis, you can pull out one or more of these templates for customizing part of the HTML.
Asciidoctor will drop back to the built-in converter to handle other elements in the document.
You don't have to feed in the whole directory of templates at once.

== General Usage Instructions

CAUTION: These usage instructions are out of date, so follow with caution.

. Ensure Asciidoctor, Slim, Haml and their dependencies are installed:

 $ gem install asciidoctor tilt haml thread_safe
   gem install slim --version 2.1.0
+
WARNING: The Slim-based templates are not yet compatible with Slim 3.

. Clone `asciidoctor/asciidoctor-backends` to get templates for rendering presentation HTML:

 $ git clone https://github.com/asciidoctor/asciidoctor-backends

. Edit `CONTENT_FILE` ( *.adoc or *.ad or ...):

  ** Slides & content per slide
  ** [Optional] Set presentation "options" at top of `CONTENT_FILE`.  The options available & their values will depend on presentation library (some examples below).

  :${Attribute}: ${Value}

. Generate HTML from Asciidoctor templates:

  .. Command Line:

 $ asciidoctor -T TEMPLATE_DIRECTORY ${options} CONTENT_FILE

  .. Build Script: use Ruby, JavaScript, Gradle, or your favorite build tool/script with presentation options

. Copy or clone presentation library (to output destination/branch):

 $ git clone PRESENTATION_LIBRARY

TIP: If you are using https://pages.github.com/[GitHub Pages], plan ahead by keeping your source files on `master` branch and all output files on the `gh-pages` branch.

.Existing Backends Templates
[cols="1a,2m,2"]
|===
|Backend |`PRESENTATION_LIBRARY` |`TEMPLATE_DIRECTORY`

|http://imakewebthings.com/deck.js/[deck.js]
|https://github.com/imakewebthings/deck.js
|replaced by: +
https://github.com/asciidoctor/asciidoctor-deck.js[asciidoctor/asciidoctor-deck.js]

|http://lab.hakim.se/reveal-js/#/[reveal.js]
|https://github.com/hakimel/reveal.js
|replaced by: +
https://github.com/asciidoctor/asciidoctor-reveal.js[asciidoctor/asciidoctor-reveal.js]

|http://paulrouget.com/dzslides/[DZSlides]
|https://github.com/paulrouget/dzslides
|`asciidoctor-backends/slim/dzslides`

|http://markdalgleish.com/projects/bespoke.js/[Bespoke.js]
|https://github.com/markdalgleish/bespoke.js
|`asciidoctor-backends/slim/bespokejs`
|===

NOTE: Some backends may be broken out into new repositories in order to manage releases independently (and potentially publish separate gems).
Aggregation of those releases back into this project may be delayed.

== Copyright and Licensing

Copyright (C) 2012-2016 Dan Allen and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.

See the <<LICENSE#,LICENSE>> file for details.
