= DZSlides backend for Asciidoctor
Dan Allen; Cédric Exbrayat

This backend is used to convert an AsciiDoc document to a HTML5 slide presentation driven by a DZSlides fork.

== Initial Setup

First, download (or git clone) the https://github.com/asciidoctor/asciidoctor-backends[asciidoctor-backends] repository to a convenient location.

 $ git clone https://github.com/asciidoctor/asciidoctor-backends.git

Next, clone the https://github.com/mojavelinux/dzslides[dzslides] repository into your working directory (where your AsciiDoc document resides).

 $ git clone https://github.com/mojavelinux/dzslides.git

If you list the files in your working directory, you should see:

....
slides.adoc
dzslides/
....

== Settings

There are some attributes that can be set at the top of the document which they are specific of +dzslides+ backend.

[cols="1m,1,1m"]
|===
|Attribute |Description |Example

|:dzslides-style: <style>
|sets the CSS theme
|watermelon

|:dzslides-transition: <transition>
|sets the type of slide transition
|fade

|:dzslides-fonts: <font>
|sets the fonts to import
|family=Cedarville+Cursive

|:dzslides-highlight: <highlight>
|sets the highlight.js theme
|monokai
|===

NOTE: You can also specify a custom stylesheet using the +stylesheet+ attribute, which can be used to customize AsciiDoc elements like section, paragraph, images, etc...

== Example

[source,asciidoc]
----
= DZSlides Demo
Your Name
:backend: dzslides
:dzslides-style: stormy
:dzslides-transition: fade
:dzslides-fonts: family=Yanone+Kaffeesatz:400,700,200,300&family=Cedarville+Cursive
:dzslides-highlight: monokai
:source-highlighter: highlightjs

[.topic.intro]
== Intro

== !

*Title*

== !

[.incremental]
* dzslides
* deckjs

[.topic.source]
== Source

[source,ruby]
--
puts 'Hello, World!'
--

[.topic.ending]
== Fin!
----

You can see some more complete examples https://github.com/mojavelinux/dzslides[here].

== Rendering

First, make sure Asciidoctor, Tilt and Slim are installed:

 $ gem install asciidoctor tilt slim

Then, to render your presentation as HTML5, simply execute the command:

 $ asciidoctor -T <backend directory> -E slim <asciidoc file>
 
So for the above dzslides backend you'd use:
 
 $ asciidoctor -T /path/to/asciidoctor-backends -E slim <asciidoc file>

== Stay Connected

If you need any other feature supported by +dzslides+ to be ported to this backend, any way to make it better or you find any bug do not hesitate to open an issue. 
